{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-consumer-group-exporter.fullname" . }}
  labels:
{{ include "kafka-consumer-group-exporter.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kafka-consumer-group-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
